[package]
name = "bee"
version = "0.3.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
colored = "2.1.0"
itertools = "0.13.0"
miniz_oxide = "0.8.0"
postcard = { version = "1.0.8", features = ["use-std"] }
serde = { version = "1.0.207", features = ["derive"] }
