[package]
name = "bee"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
postcard = { version = "1.0.8", features = ["use-std"] }
serde = { version = "1.0.207", features = ["derive"] }
